### ISSUE TITLE
Geyser-Fabric MSA support

### ISSUE THREAD

**Issue by Gaming32** [rtm516/MCXboxBroadcast#1]
Suggestion: broadcast Open to LAN worlds to Xbox friends that are in the same Microsoft account as the Java Edition player.

**Comment by rtm516** [comment]
Due to how auth has to be done in a very specific way for this to work you would just have to auth using it anyway and we couldn't capture the token for the logged-in player. So currently if the Fabric host just checked their console and followed the auth steps then it would work as expected.

**Comment by Gaming32** [comment]
So basically what you're saying is that it already does this with Open to LAN?
