### ISSUE TITLE
Microsoft account appears to have been banned

### ISSUE THREAD

**Issue by jschenke488** [rtm516/MCXboxBroadcast#106]
I'm not surprised this happened, just reporting that Microsoft is banning accounts running MCXboxBroadcast.
```
[Geyser-Spigot] [mcxboxbroadcast] [Primary Session] Failed to get/refresh auth token
net.raphimc.minecraftauth.responsehandler.exception.MsaRequestException: status: 400 Bad Request, error: invalid_grant, error message: User account is found to be in service abuse mode.
```

**Comment by rtm516** [comment]
Can you try logging into the Xbox website with the account and seeing if that makes a difference?

**Comment by refractored** [comment]
Same thing happened to me, when logging back in it states there's been some suspicious activity that may violate the terms of service, and it asks me to verify its me.

**Comment by jschenke488** [comment]
> Can you try logging into the Xbox website with the account and seeing if that makes a difference?

![image](https://github.com/user-attachments/assets/94bb4e03-8ef3-485f-9eb5-4cdf80ac390a)

**Comment by rtm516** [comment]
Just go through the steps and it should unlock with no further issues
