### ISSUE TITLE
Broadcast issue

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [rtm516/MCXboxBroadcast#110]
It says [16:57:55 INFO]: [Geyser-Spigot] [mcxboxbroadcast] [Auth] Got XBL User+Title+XSTS Token, expires: 2024-07-26T08:57:55.447-04:00[America/Detroit]
 and the bot don’t go online or it don’t let me join, using aternos.

**Comment by rtm516** [comment]
Please update to build 39
