### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by druu12** [rtm516/MCXboxBroadcast#111]
cant connect to server through friends list but i can join through add server

**Comment by rtm516** [comment]
Likely the remote address in the tools config needs changing from auto to the IP you can join the server with. Please try changing rhat

**Comment by druu12** [comment]
it still just says connecting to multiplayer game until it says unable to connect

**Comment by rtm516** [comment]
Please provide a `mcxboxbroadcast sessiondump` files and the IP for the server

**Comment by druu12** [comment]
when i try to do the /mcxboxbroadcast dumpsession command it just says unkown or incomplete command

**Comment by rtm516** [comment]
Suggests the tool isnt running, unless you are using standalone in which case it's just `dumpsession`

If your using the extension then please provide logs for your server.

**Comment by druu12** [comment]
[latest.log](https://github.com/user-attachments/files/16425456/latest.log)

**Comment by rtm516** [comment]
Ah from server console, you shouldnt put the `/` at the start of the command

**Comment by druu12** [comment]
[currentSessionResponse.json](https://github.com/user-attachments/files/16425529/currentSessionResponse.json)

**Comment by rtm516** [comment]
Looks like that file didn't upload properly, can you try again?

**Comment by druu12** [comment]
[currentSessionResponse.json](https://github.com/user-attachments/files/16425577/currentSessionResponse.json)

**Comment by rtm516** [comment]
Thanks, looks like you have put both the IP and Port in the address box

This is likely the settings you want

remote-address: 147.185.xxx.xxx
remote-port: 3642
