### ISSUE TITLE
Feature request Auto updating

### ISSUE THREAD

**Issue by OdymarGamer** [rtm516/MCXboxBroadcast#112]
Hi is there anyway the plugin or the standalone can be automaticly updated? 
and is there any chance you can add it ?

**Comment by rtm516** [comment]
Geyser extensions have no method for auto updating. For standalone same issue but also changing a jar while it's running causes issues, if you want auto updates I suggest using the docker container and using an external tool like https://containrrr.dev/watchtower/ to update it.

Most updates are minor features and unless your having issues it's likely you don't need to update.

**Comment by OdymarGamer** [comment]
thx
