### ISSUE TITLE
API-version is wrong still

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [rtm516/MCXboxBroadcast#113]
Using latest version for server and stuff and the mcxbox broadcast still say wrong api version cannot load

**Comment by rtm516** [comment]
Update Geyser

**Comment by lolwhatdidigetbanned** [comment]
> Update Geyser

That’s what I just did and it fixed

**Comment by lolwhatdidigetbanned** [comment]
> Update Geyser

And I didn’t see the reply so I just tried to update geyser now it’s fixed
