### ISSUE TITLE
Xbox Broadcast disconnects after a while

### ISSUE THREAD

**Issue by AntonZgr** [rtm516/MCXboxBroadcast#12]
[02:04:28] [Geyser Scheduled Thread-2-1/INFO]: [Geyser-Spigot] [MCXboxBroadcast] Connection to websocket lost, re-creating session...

This shows up in the console and the Xbox Session is unreachable, this happens after a few hours of running and every single time. It won't reconnect either. 

Here is some information about my server: https://dump.geysermc.org/48CLERhZLI5wiQqSonsFT7dmmQ1XtY2z

Edit: I'm using the geyser extension

**Comment by rtm516** [comment]
Connection getting disconnected is semi-expected but it not being able to re-connect is intresting and deffo needs more looking into.

**Comment by rtm516** [comment]
Unable to replicate and not had any other issues mentioned since. Please re-open if it still occurs

**Comment by UltraHispeed-Elite** [comment]
I’m having a similar issue on a fabric server but I don’t get the same message it just stops showing up after a few hours

**Comment by CobreDev** [comment]
I'm running it as a Geyser extension, and have the same issue after an unknown amount of time. I don't see anything in the logs

**Comment by UltraHispeed-Elite** [comment]
> 

hey fixed it just use the standalone instead of the extension, the standalone has a auto restart built in
