### ISSUE TITLE
Failed to ping server

### ISSUE THREAD

**Issue by blink7** [rtm516/MCXboxBroadcast#120]
There is a similar [issue before](https://github.com/rtm516/MCXboxBroadcast/issues/75), but I didn't find any useful information there, so I opened a new one.

Using the latest 48 build (standalone) for the vanilla bedrock server I faced with the "Failed to ping server" error.  
I can ping it manually from [mcsrvstat.us](https://mcsrvstat.us/bedrock) and play without any problems. However this tool doesn't...
![capture20240810143015561](https://github.com/user-attachments/assets/9a98c11a-9996-4e63-bf1c-b9e36856e051)
![capture20240810143712193](https://github.com/user-attachments/assets/5ec019a7-cf38-42ec-a142-4bbdc368b8d1)

If there are any specific incoming/outgoing ports that need to be opened or other required settings, I'll be grateful for help🙇‍♂️

**Comment by rtm516** [comment]
This is likely a routing problem on your network, meaning whatever the tool is running on cant reach the server over the IP that your domain name resolves to.
If there's another IP you can reach it over could you try with that and see if it pings?
If it does then I can make some code changes to support different ping and broadcast IPs

**Comment by blink7** [comment]
Yeah, I have another IP, but same problem...
It's worth to mention I'm using [reverse proxy](https://github.com/fatedier/frp) to expose the server to the Internet (behind a NAT). This is probably the reason why this tool can't ping the server?

**Comment by rtm516** [comment]
Thats quite likely the problem, all I can suggest is you play around and with diff IP combos and see if you can get it to ping the server. Its using fairly standard stuff to ping the server and the only reason it wouldn't be able when the server is up is if it cant reach it due to routing issues.

**Comment by blink7** [comment]
Well, I tried all my IPs, tried specifying the IP address directly (not DNS name), but no success.
Is it possible to make it ping like mcsrvstat.us does instead?

**Comment by rtm516** [comment]
Behind the scenes they do the same thing but `mcsrvstat.us` is pinging from outside your network

**Comment by blink7** [comment]
I moved the tool to one of the cloud servers I use for proxy reverse and it finally worked!
Thank you for help and sorry taking up your time🙇‍♂️
