### ISSUE TITLE
worked at first then never worked again

### ISSUE THREAD

**Issue by tyree123** [rtm516/MCXboxBroadcast#123]
it worked at the start but then it stopped working and never worked again anyway you can reach me on discord please 
![1`1](https://github.com/user-attachments/assets/4e96799e-9dbe-4fe7-bf86-c77d925d3d1d)
![122](https://github.com/user-attachments/assets/f693e6ba-c4fb-4d94-b522-19dfc1c9864f)
![33](https://github.com/user-attachments/assets/bb2cd759-def1-467e-9e89-8fcd4fe1f795)
please reach out to me

**Comment by tyree123** [comment]
![Uploading `````.PNG…]()

**Comment by tyree123** [comment]
its like it was working but it kept stopping and i would restart it and now it dosnt work at all please help

**Comment by superJK92iscool** [comment]
Well currently the newest Minecraft bedrock version doesn't work with MCSboxBroadcast as of right now anyway

**Comment by rtm516** [comment]
Please attach a full latest.log from the tool, and also see above

**Comment by tyree123** [comment]
[2024-08-13-2.log.gz](https://github.com/user-attachments/files/16606258/2024-08-13-2.log.gz)
[latest.log](https://github.com/user-attachments/files/16606259/latest.log)
[2024-08-13-1.log.gz](https://github.com/user-attachments/files/16606260/2024-08-13-1.log.gz)

**Comment by tyree123** [comment]
discord
like i said it was working but it kept turning its self off and then i would have to restart it and now it dosnt want to work at all

**Comment by superJK92iscool** [comment]
> Well currently the newest Minecraft bedrock version doesn't work with MCXboxBroadcast as of right now anyway

Well it won't work anyway due to this

**Comment by rtm516** [comment]
> [2024-08-13-2.log.gz](https://github.com/user-attachments/files/16606258/2024-08-13-2.log.gz) [latest.log](https://github.com/user-attachments/files/16606259/latest.log) [2024-08-13-1.log.gz](https://github.com/user-attachments/files/16606260/2024-08-13-1.log.gz)

Looks like the ip/port in the config isn't pointing to an online geyser/bedrock server

**Comment by tyree123** [comment]
thats the thing it was working on latest veerson of minecraft bedrock i was able to join it about 5 times

**Comment by tyree123** [comment]
explain? how i can fix

**Comment by superJK92iscool** [comment]
Maybe it works on the Standalone version but to the Geyser extension for some odd reason?

**Comment by tyree123** [comment]
![```](https://github.com/user-attachments/assets/51a1a07d-8552-4676-bd00-127199809e18)

**Comment by tyree123** [comment]
do i change that?

**Comment by superJK92iscool** [comment]
Remove the image and hide the ip, people can join with that

**Comment by superJK92iscool** [comment]
unless you want it to be public

**Comment by tyree123** [comment]
can the ip be letters too

**Comment by tyree123** [comment]
seems-mo.gl.at.ply

**Comment by tyree123** [comment]
its a public one

**Comment by superJK92iscool** [comment]
> can the ip be letters too

In theory they can

**Comment by superJK92iscool** [comment]
Is they Geyser server running, I can't even join through the ip on bedrock

**Comment by tyree123** [comment]
please help what can i do to fix it 
do you guys have discord

**Comment by tyree123** [comment]
i fixed it i think i hope it stays on

**Comment by tyree123** [comment]
its stuck on loading resources now

**Comment by superJK92iscool** [comment]
I can't say I've had that happen (because I haven't, to be fair I have only tried joining it locally)

**Comment by tyree123** [comment]
bruth this is so annoying now it just says connecting to multiplayer game im finna go throw C4 all over my pc

**Comment by superJK92iscool** [comment]
That is the current issue

**Comment by tyree123** [comment]
oh

**Comment by CoveWolf** [comment]
This new update almost seems intentional to stop bots like MCXboxBroadcast. I don't want to jump to conclusions but it seems this update was partially made to prevent those who want to create/host their own servers and be able to play them on console.

**Comment by tyree123** [comment]
this is why i dislike minecraft bedrock i used to host major servers smp related and ever time its hard to keep the server together in the past of my hosting i didnt have to deal with addons not loading or crashing the server but now its gotten worst

**Comment by S-SHI777** [comment]
Is the removal of the pdb file in this minecraft version related to this issue?

**Comment by rtm516** [comment]
Closing in favour of https://github.com/rtm516/MCXboxBroadcast/issues/122

Once that's resolved if your still facing issues please head over to discord
