### ISSUE TITLE
The 1.21.20 update broke mcxboxbroadcast

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [rtm516/MCXboxBroadcast#124]
Please fix it, (sorry for duplication)

**Comment by CoveWolf** [comment]
He's trying to.

**Comment by HealingHalo8** [comment]
hey the developer for this plugin is current out of town, but is attempting to fix it, he will have it up as soon as possible.

**Comment by rtm516** [comment]
Duplicate of https://github.com/rtm516/MCXboxBroadcast/issues/122
