### ISSUE TITLE
New client hotfix to come out for 1.21.20

### ISSUE THREAD

**Issue by CoveWolf** [rtm516/MCXboxBroadcast#125]
Mojang has reported on twitter that they will be releasing a hotfix for 1.21.20. This is aimed to solve connectivity issues with realms, which is experiencing really high load times. Maybe this will help with the connection issues of MCXboxBroadcast.

https://x.com/mojangstatus/status/1823715437827224041?s=46

**Comment by onebeastchris** [comment]
Realms are not really related to what Mcxboxbroadcast is doing, but thanks for the info! For the future, please use the discord server (link on the readme) if possible. Thanks :)
