### ISSUE TITLE
Unable to start extension

### ISSUE THREAD

**Issue by onebeastchris** [rtm516/MCXboxBroadcast#23]
Hey! ever since protocol 3.0; i get this error when trying to run the master version of the extension:
https://paste.gg/p/anonymous/8715e23da8b842398a4e81a8af1b303a
This does not occur with the PR #21 ; however; it does not start.

**Comment by PizzaThatCodes** [comment]
Any chance could I get both .jar file you are currently using? I have created a velocity server (same version as you Snapshot 250) and I downloaded both newest versions of MCXboxBroadcast extensions and it's working just fine.

Maybe it was still downloading and you dragged it somewhere else which caused it to install weird? But I wouldn't really know until I see the .jar.

**Comment by onebeastchris** [comment]
Okay I found something.. interesting
Apparently, the extension stops showing log messages whenever I use more than one extension at once - as for the ClassNotFound error, a re-download fixed that

**Comment by onebeastchris** [comment]
resolved by https://github.com/GeyserMC/Geyser/commit/b48d4a0625ed9a269d81fea6e535345bce01c0af - was an issue with having multiple extensions.
