### ISSUE TITLE
Extension doesn't print linking code

### ISSUE THREAD

**Issue by s3tupw1zard** [rtm516/MCXboxBroadcast#24]
Hello,

I installed this extension on my Geyser Spigot Plugin but it doesn't seem to load correctly after changing the host where my Minecraft server runs.

Geyser prints that the extension is successfully loaded but I can't get the new code for logging in.

I noticed that it currently doesn't work when I opened Minecraft Bedrock as the Broadcast wasn't showing up.
Since then I tried to delete all Geyser configs, deleted the extensions configs but nothing seems to work.

I've also read that clearing the cache may help. But what folder do I need to delete?

Thanks for help

**Comment by rtm516** [comment]
If the linking code isn't showing then likely the server can't connect to Microsoft. Please provide a full server log file.

**Comment by rtm516** [comment]
Fixed by https://github.com/rtm516/MCXboxBroadcast/commit/c7f5c087504af01b9fbb17996597c275ccd09a25
