### ISSUE TITLE
Feature Request: Custom Session Info for Extension, just like in Standalone

### ISSUE THREAD

**Issue by TBYT** [rtm516/MCXboxBroadcast#25]
Currently the only customization you can do in the extension is the port and address. In the standalone you can do both of those as well as host-name, world-name, version, players, max-players, and protocol (which i leave on default.)

I'd like to see this started on after https://github.com/rtm516/MCXboxBroadcast/pull/21 is finished.

**Comment by rtm516** [comment]
These are all pulled from Geyser. Hence why they are not configurable in the extension config, the few that can be changed nicely are editable in the Geyser configuration.

**Comment by TBYT** [comment]
> These are all pulled from Geyser. Hence why they are not configurable in the extension config, the few that can be changed nicely are editable in the Geyser configuration.

oh yeah you're right, thanks for letting me know.
