### ISSUE TITLE
cannot connect world online

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [rtm516/MCXboxBroadcast#30]
so I've been running tests with this extension and they have all worked so far, or all the tests that I can do on the same network, unfortunately everytime I try to conduct the test with a friend online they cannot connect, is there any online networking I need to do for the server or am I doing something wrong?

**Comment by SonnenPingu** [comment]
The extensions must be connected to xbox live. 

It is displayed in the server console, a code and a link.

Once this is done, you will find the files xbox-live.token and two other files under /geyser/extensions/MCXboxBroadcast. One of them is the config file. 

I would adapt this to the server IP and port so don't leave it on auto. 

Then enter Geyser reload into the console And if it says: Created xbox session then allws worked. 

Then people only need the gamertag from the xbox account and can join with it

**Comment by UltraHispeed-Elite** [comment]
did everything it works on my own local internet,  but when someone on an alternative network tries to join they can't

**Comment by SonnenPingu** [comment]
No extension Error. Your configuration or setting Are not correct. 

Port sharing, routers, etc.

**Comment by marissa999** [comment]
> Port sharing, routers, etc.

Are there any ports that one might need to open/share besides the default mcbedrock ones? (udp 19132-19133)

**Comment by rtm516** [comment]
You will need to alter the `remote-address` in the extension configuration to the public IP of your server.

If your using the standalone version then edit the `ip` and `port` under `session-info`
