### ISSUE TITLE
Unable to connect to world [Standalone]

### ISSUE THREAD

**Issue by marissa999** [rtm516/MCXboxBroadcast#31]
This issue might be similar to #15 but I on the other hand do not have any logs at all, possibly due to me using the standalone version. 

My setup is probably a bit cursed. I run a Minecraft Java (PaperMC paper-1.20.1-21) server. This server however is not running 24/7, instead I expose a proxy, which puts the server to sleep when nobody is connected (https://github.com/timvisee/lazymc). I also want Bedrock players to connect to my server, therefore I run Geyser. But because the java server is not running 24/7 I run the Geyser standalone, which then connects to the lazymc proxy. 

This all works:
- mc-client java -> lazymc -> papermc java server
- mc-client bedrock -> geyser -> lazymc -> papermc java server

Now I wanted to add mcxboxbroadcast to that mix, making it comfortable for people to join the minecraft server, especially from consoles. This however does not seem to work. I made a new Microsoft-Account + XBox-Account and managed to connect the mcxboxbroadcast to it. I also successfully managed to add myself as a friend to that application. That application should connect to my geyser-server. This does seem to "kind of" work. On my phone (Android) I can go to the friends list and under "Joinable Friends" I can see my new account. I can also see the motd "Server is sleeping - Join to start it up". So it seems like it knows about the server. However connecting to it only results in "Unable to connect to world". I do not get any logs in mcxboxbroadcast, all it prints is "Updated session!" every 30 seconds. My geyser standalone server also prints nothing, indicating that the mcxboxbroadcast does not attempt to connect to the server. Running mcxboxbroadcast with `debug: true` does not yield anything useful, now it prints `Websocket message` with `"resourceType":"mpsd/session"` (which I assume is basically the what happens in the background for "Updated session!")

I have no clue what I could provide for meaningful information. There is nothing in any debug logs. 

Versions:
OS: Arch Linux (btw)
Java: openjdk version "20.0.1" 2023-04-18
MCXboxBroadcast: Build #19 (27 Mar 2023, 09:40:44)
Geyser Standalone: Geyser version 2.1.1-SNAPSHOT
PaperMC: paper-1.20.1-21
LazyMC: v0.2.10

**Comment by rtm516** [comment]
You will need to alter the `remote-address` in the extension configuration to the public IP of your server.

If your using the standalone version then edit the `ip` and `port` under `session-info`

**Comment by marissa999** [comment]
Oh, I see, the public IP.

What would be the best approach however for people who use a dynamic dns? I do have a domain name I could point to, but hardcoding an IP wouldnt work. Any good way to work around that?

**Comment by rtm516** [comment]
A domain name should work although ive not tested it

**Comment by marissa999** [comment]
i can confirm, it does indeed work! ty!
