### ISSUE TITLE
Unknown channel option 'IP_DONTFRAG'

### ISSUE THREAD

**Issue by jefflima1** [rtm516/MCXboxBroadcast#32]
Hello, I'm getting this error, constant on the console, the connections on the server are being made correctly without any problem using the standalone version, but this error appears

[WARN] Unknown channel option 'IP_DONTFRAG' for channel '[id: 0xd9a9d65a]'

I would like to know if it's normal, or what can be done to solve it, or if it doesn't impact anything...

**Comment by rtm516** [comment]
This isn't an issue with MCXboxBroadcast

**Comment by jefflima1** [comment]
I'm running the standalone version, I get this error in the software console, what could it be?

**Comment by jefflima1** [comment]
![Capturar](https://github.com/rtm516/MCXboxBroadcast/assets/106811319/63c13e86-d7ae-44d6-8030-9a5685fdf4f2)

**Comment by rtm516** [comment]
Oh it's in the standalone version, I'll have to look into this

**Comment by Kodey-Kayla** [comment]
can confirm, running latest standalone as of 2023-07-24 and getting the same error, still seems to work fine though

as a sidenote, I switched to standalone because the extension version disappears from the friends list after a few hours. hoping standalone will be more stable.

**Comment by UltraHispeed-Elite** [comment]
The stand-alone stayed connected for about two weeks and no longer works for me no matter how many times I try restarting it

**Comment by rtm516** [comment]
@Kodey-Kayla @UltraHispeed-Elite Please see #41

**Comment by rtm516** [comment]
@jefflima1 How are you starting the tool? I cant seem to locate the source of this other than misconfiguration when starting.

Could you also provide the name and version of the OS you ran it on? 
Java version would also be useful

**Comment by rtm516** [comment]
This is due to IP_DONTFRAG not being supported on Windows and can safely be ignored.
