### ISSUE TITLE
Staying connected 

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [rtm516/MCXboxBroadcast#33]
So I’m setting up a server with this extension and I’ve kept the server up for a bit but the broadcast extension keeps going offline after a few hours up is there a way I can keep the server being broadcasted through Xbox live indefinitely?

**Comment by UltraHispeed-Elite** [comment]
yeah the standalone stopped working and I'm hoping there is something I can do to keep it online

**Comment by rtm516** [comment]
Please follow the instructions in #41 to help in resolving this issue.
