### ISSUE TITLE
Websocket disconnected error

### ISSUE THREAD

**Issue by BlockingBongo97** [rtm516/MCXboxBroadcast#36]
Roughly two hours after the session is started, the websocket disconnects. After turning on geyser's debug mode, I received this message in the console when it would disconnect: '[MCXboxBroadcast] Websocket disconnected:  (1006)'. Reloading geyser or restarting my server does bring it back, but unfortunately it disconnects again after another two hours.

**Comment by UltraHispeed-Elite** [comment]
yeah i'm having the same issue it started a couple days ago after being online for about 2 weeks and now it just won't connect at all when I try to restart it it just disconnects after a few minutes

**Comment by rtm516** [comment]
> [MCXboxBroadcast] Websocket disconnected: (1006)

Along with this is there any websocket errors?

According to the internet 1006 is when the client terminates the connection, so that's your server in this case.

**Comment by rtm516** [comment]
Please follow the instructions in #41 to help in resolving this issue.
