### ISSUE TITLE
disconnection

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [rtm516/MCXboxBroadcast#38]
ok so I've used both the standalone and extension for this and I've have the same issue where they both disconnect, the Extension disconnects in a matter of hours, and when I used the Standalone it worked fine for a little over two weeks and now all of the sudden it just refuses to work now it barely stays connected for more than five minutes.

**Comment by rtm516** [comment]
Please follow the instructions in #41 to help in resolving this issue.
