### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by Creeperz653** [rtm516/MCXboxBroadcast#4]
The problem is when you join a server that uses a server selector item it doesn't load but when you join it using dns like geyser connect it works or using geyser connects mcxb because geyser connects mcxb redirects to the server like the dns so it isn't a issue for them but if the server uses mcxb directly the item selector disappears the item selector plugin I use is cross plats

**Comment by Creeperz653** [comment]
![image](https://user-images.githubusercontent.com/76449952/178459821-04158852-55da-497b-bdd0-b029d21f2171.jpeg)
Example of it not loading

**Comment by rtm516** [comment]
Clients connecting using this tool directly connect to the end server and not via any DNS or other server transfer/proxy method so that it won't affect the client <-> server interaction.

This is likely an issue with your server or the plugin.
