### ISSUE TITLE
"Unable to connect to world"

### ISSUE THREAD

**Issue by ha-rriz** [rtm516/MCXboxBroadcast#49]
I don't know what I'm doing wrong? I can't host my server on 1.20.2 because of how buggy it is, so I have to use 1.19.4 and it just simply errors with that

**Comment by rtm516** [comment]
You will need to change the `remote-address` in the tools config to your servers IP, it tries to automatically get it but its not always successful depending on how the server is configured.

**Comment by ha-rriz** [comment]
Wow! Fast response. Thanks dude, I'll test it out.

**Comment by ha-rriz** [comment]
It worked! Thanks.
