### ISSUE TITLE
Whitelist command signature change

### ISSUE THREAD

**Issue by mbicknese** [rtm516/MCXboxBroadcast#52]
It looks like this project can no longer be built due to https://github.com/GeyserMC/Floodgate/pull/456 being merged. The `WhitelistUtils.addPlayer` method now expects `SpigotVersionSpecificMethods` as the third argument.

**Comment by rtm516** [comment]
You can use the pre-built version on the GitHub release and disable that feature. I can look into fixing this but in all likelihood I will remove it as it's not really a supported use of floodgate.

**Comment by mbicknese** [comment]
Oh, that's fine.

I was actually trying to solve a bug I'm having with running the extension in Docker. My guess is that it's not picking up on the correct IP address. I'll figure that out (or create a build with a hardcoded IP if really needed).

Just wanted to let you know building is not currently possible.

**Comment by rtm516** [comment]
There is `remote-address` and `remote-port` in the config to change it if not automatically picked up. Also bedrock doesn't like if the server is listening on a different port to what you connect on, it can cause issues.

**Comment by Tim203** [comment]
Yeah it wasn't really intended to be used externally. But if there is an use-case then I'm fine with exposing an API for it.
