### ISSUE TITLE
mcxboxbrodcast continues to run after server stops (Extension)

### ISSUE THREAD

**Issue by ItsmagmaMan09** [rtm516/MCXboxBroadcast#53]
I have a fabric server with geyser and mcxboxbrodcast and when I stop the server the extension keeps running making it appear the server is online to bedrock players

**Comment by Stein-N** [comment]
This also causes the issue that the server can't be started again(on some server software).

Had a server running on GPortal and on my Home Server over Crafty (Casa OS / Debian) and on both i had that issue
