### ISSUE TITLE
Geyser-Bungee+Extension whitelist issue

### ISSUE THREAD

**Issue by RADICALAdrift** [rtm516/MCXboxBroadcast#55]
Hi There,

I currently have a bungee network with 2 whitelisted backend servers running behind it, 
Geyser+Floodgate & your extension are running on the bungee with Floodgate on the backend servers

My problem is i have it setup where people can add the account used and they will get auto-whitelisted,
But that doesn't work since the extension is on the bungee rather than the backend servers

Any solutions would be greatly appreciated, I would rather not have to complicate my setup to accomidate the extension if at all possible

**Comment by RADICALAdrift** [comment]
Even if i have to add a whitelist plugin to my bungeecord that's fine though the only issue with that is if anyone gets added to the whitelist they could get on both my servers using /server <server name> unless i restrict access to that

**Comment by RADICALAdrift** [comment]
I would be right to assume the extension uses the standard whitelist commands such as:

/whitelist add <name>
/whitelist on
/whitelist off
/whitelist remove <name>
/whitelist reload

**Comment by onebeastchris** [comment]
it does not - the extension hooks into the floodgate whitelist function; which only exist on spigot (https://github.com/rtm516/MCXboxBroadcast/blob/master/bootstrap/geyser/src/main/java/com/rtm516/mcxboxbroadcast/bootstrap/geyser/MCXboxBroadcastExtension.java#L188-L199). Using the normal whitelist commands would not work, since we're not dealing with java but bedrock players instead.

**Comment by RADICALAdrift** [comment]
Ah that's right, I've also come to the realization that having the autowhitelist on defeats the purpose security of the whitelist in the first place

**Comment by RADICALAdrift** [comment]
If i were running both servers separately then there wouldn't be an issue but bungee'ing them together made more sense from a management standpoint

**Comment by onebeastchris** [comment]
no

**Comment by RADICALAdrift** [comment]
Okay, figured as much and was curious.. feel free to close the issue now
