### ISSUE TITLE
Playstation compatability

### ISSUE THREAD

**Issue by SoundMeister** [rtm516/MCXboxBroadcast#56]
I'm tried this with a playstation user and they were having issues with the friend connection showing up. Is there a way to make it work with them? Not sure if it's ust my friend or not.

**Comment by rtm516** [comment]
The tool should work out the box with playstation users as for multiplayer you have to login to an Xbox account as far as I'm aware.

**Comment by SoundMeister** [comment]
I'm very sorry I resolved this issue with a restart of my internet
