### ISSUE TITLE
Impossible to connect

### ISSUE THREAD

**Issue by Davidx01** [rtm516/MCXboxBroadcast#62]
When i try to join the bot's playing server it says "impossible to connect". Its not a geyser issue 'cause when i join from bedrock from my pc it works

**Comment by rtm516** [comment]
Change the remote address in the mcxboxbroadcast config to your servers IP you connect to.

**Comment by rtm516** [comment]
Please provide a geyser dump and a copy of the extensions config file along with the IP and port used to connect normally
