### ISSUE TITLE
cant join

### ISSUE THREAD

**Issue by Davidx01** [rtm516/MCXboxBroadcast#63]
it says impossible to connect, geyser is setupped correctly cuz i can join from pc bedrockedition

**Comment by Davidx01** [comment]
only when connectiong with the bot it shows error

**Comment by onebeastchris** [comment]
your issue was replied to with a solution here https://github.com/rtm516/MCXboxBroadcast/issues/62#issuecomment-1869422169 - there's no need to open a new one

**Comment by Davidx01** [comment]
It's not solved I still have this errror

Il mar 26 dic 2023, 11:55 chris ***@***.***> ha scritto:

**Comment by rtm516** [comment]
Please continue using the old post then.
