### ISSUE TITLE
having to relink xboxconnect to my microsoft account almost daily

### ISSUE THREAD

**Issue by shawn695** [rtm516/MCXboxBroadcast#64]
[message.txt](https://github.com/rtm516/MCXboxBroadcast/files/14001856/message.txt)

also doing the reload command would cause errors with geyser, kicking all members from the server

**Comment by rtm516** [comment]
This is not something I can help, if Auth is failing then the token is getting invalidated by Microsoft which I cannot fix. The tool already tries to get a new token and if that fails it asks you to login again.

**Comment by shawn695** [comment]
anything i can do to prevent this ?
and the reload command causing those errors with geyser ?

**Comment by rtm516** [comment]
Make sure you haven't turned on any extra security settings on the account used and make sure the account isn't being used elsewhere.
