### ISSUE TITLE
Failed to get authentication token

### ISSUE THREAD

**Issue by Mundo-Minecraft** [rtm516/MCXboxBroadcast#74]
Hello, I am recently having a problem with the plugin. When I tried to access Microsoft to write the code 

"[pool-161-thread-1/INFO]: [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] To log in, use a web browser to open the page https:// www.microsoft.com/link and enter the code ACBWCYEZ to authenticate." 

it gives me the following error 

"[09:58:15] [Thread-42/WARN]: [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] Failed to get authentication token from device code: com.rtm516.mcxboxbroadcast.core.exceptions.LiveAuthenticationException: Failed to get authentication token while waiting for device: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. (invalid_grant)
[09:58:15] [Thread-42/INFO]: [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] MSA authentication response is null, please login again"

I have tried reinstalling and configuring geyser and mcxboxbroadcast with the same result.

Thank you.

**Comment by PizzaThatCodes** [comment]
Does the account have a xbox profile created?

**Comment by rtm516** [comment]
Please login to https://account.xbox.com/en-gb/Profile?xr=mebarnav and make sure your profile is setup
