### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by L642207** [rtm516/MCXboxBroadcast#84]
The world shows but does not connect on the Geyser Extension version.

**Comment by sennby** [comment]
same issue, i cant dumpsession either
I tried via velocity geyser, moving geyser to standaloneand trying, and the standalone version of mcxbox, none work.

**Comment by rtm516** [comment]
Please provide logs and a session dump (update for that to work)

**Comment by L642207** [comment]
Geyser dump or just the extension?

**Comment by rtm516** [comment]
Both would be good

**Comment by L642207** [comment]
I couldn’t figure out how to do the extension dump, but here is the Geyser dump.

{
    "versionInfo": {
        "name": "Geyser",
        "version": "2.3.2-SNAPSHOT (git-master-09c0ada)",
        "javaName": "OpenJDK 64-Bit Server VM",
        "javaVendor": "Eclipse Adoptium",
        "javaVersion": "21.0.3+9-LTS",
        "architecture": "amd64",
        "operatingSystem": "Linux",
        "operatingSystemVersion": "6.1.0-11-amd64",
        "network": {
            "dockerCheck": false,
            "internalIP": "***"
        },
        "mcInfo": {
            "bedrockVersions": [
                "1.20.80/1.20.81",
                "1.21.0"
            ],
            "bedrockProtocols": [
                671,
                685
            ],
            "defaultBedrockProtocol": 685,
            "javaVersions": [
                "1.20.5",
                "1.20.6"
            ],
            "javaProtocol": 766
        }
    },
    "cpuCount": 24,
    "cpuName": "AMD Ryzen 9 3900X 12-Core Processor",
    "systemLocale": "en_US",
    "systemEncoding": "UTF-8",
    "gitInfo": {
        "buildNumber": "559",
        "git.commit.id.abbrev": "09c0ada",
        "git.commit.id": "09c0ada50216e1a163b22cccdce5b0657085ebd6",
        "git.branch": "master",
        "git.remote.origin.url": "https://github.com/GeyserMC/Geyser"
    },
    "config": {
        "autoconfiguredRemote": true,
        "bedrock": {
            "address": "0.0.0.0",
            "port": 2215,
            "broadcast-port": 2215,
            "clone-remote-port": true,
            "motd1": "The Iridium Empire",
            "motd2": "A city of many fine qualities.",
            "server-name": "Iridium Empire Roleplay",
            "compression-level": 6,
            "enable-proxy-protocol": false,
            "proxy-protocol-whitelisted-ips": []
        },
        "remote": {
            "address": "***",
            "port": 2215,
            "auth-type": "FLOODGATE",
            "use-proxy-protocol": false,
            "forward-hostname": false
        },
        "metrics": {
            "enabled": true,
            "uuid": "76cba9bc-7a23-4ee3-aea5-df9281738c74"
        },
        "disableCompression": true,
        "saved-user-logins": [
            "ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername",
            "ThisOtherExampleUsernameShouldAlsoBeLongEnough"
        ],
        "floodgate-key-file": "key.pem",
        "command-suggestions": true,
        "passthrough-motd": true,
        "passthrough-player-counts": true,
        "legacy-ping-passthrough": false,
        "ping-passthrough-interval": 3,
        "forward-player-ping": false,
        "max-players": 100,
        "debug-mode": false,
        "allow-third-party-capes": false,
        "show-cooldown": "title",
        "show-coordinates": true,
        "disable-bedrock-scaffolding": false,
        "emote-offhand-workaround": "DISABLED",
        "allow-third-party-ears": false,
        "default-locale": null,
        "cache-images": 0,
        "allow-custom-skulls": true,
        "max-visible-custom-skulls": 128,
        "custom-skull-render-distance": 32,
        "add-non-bedrock-items": true,
        "above-bedrock-nether-building": false,
        "force-resource-packs": true,
        "xbox-achievements-enabled": false,
        "log-player-ip-addresses": true,
        "notify-on-new-bedrock-update": true,
        "unusable-space-block": "minecraft:barrier",
        "pending-authentication-timeout": 120,
        "scoreboard-packet-threshold": 20,
        "enable-proxy-connections": false,
        "mtu": 1400,
        "use-direct-connection": true,
        "disable-compression": true,
        "config-version": 4
    },
    "floodgate": {
        "gitInfo": null,
        "config": null
    },
    "userPlatforms": {},
    "connectionAttempts": 0,
    "hashInfo": {
        "md5Hash": "67e108152ea52e3cc023cab60f5d8083",
        "sha256Hash": "ec04f1a7ffc07765548153df13d2319ed086aabf37b5e55a0ef9a3576bf94e66"
    },
    "ramInfo": {
        "free": 284,
        "total": 1108,
        "max": 7796
    },
    "logsInfo": null,
    "bootstrapInfo": {
        "platform": {
            "platformName": "Spigot"
        },
        "platformName": "Purpur",
        "platformVersion": "1.20.6-2227-79d199c (MC: 1.20.6)",
        "platformAPIVersion": "1.20.6-R0.1-SNAPSHOT",
        "onlineMode": true,
        "serverIP": "0.0.0.0",
        "serverPort": 2215,
        "plugins": [
            {
                "enabled": true,
                "name": "ViaVersion",
                "version": "4.10.2",
                "main": "com.viaversion.viaversion.ViaVersionPlugin",
                "authors": [
                    "_MylesC",
                    "creeper123123321",
                    "Gerrygames",
                    "kennytv",
                    "Matsv",
                    "EnZaXD",
                    "RK_01"
                ]
            },
            {
                "enabled": true,
                "name": "LuckPerms",
                "version": "5.4.102",
                "main": "me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin",
                "authors": [
                    "Luck"
                ]
            },
            {
                "enabled": true,
                "name": "Vault",
                "version": "1.7.3-b131",
                "main": "net.milkbowl.vault.Vault",
                "authors": [
                    "cereal",
                    "Sleaker",
                    "mung3r"
                ]
            },
            {
                "enabled": true,
                "name": "PlaceholderAPI",
                "version": "2.11.6",
                "main": "me.clip.placeholderapi.PlaceholderAPIPlugin",
                "authors": [
                    "HelpChat"
                ]
            },
            {
                "enabled": true,
                "name": "floodgate",
                "version": "2.2.3-SNAPSHOT (b109-49bd564)",
                "main": "org.geysermc.floodgate.SpigotPlugin",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "enabled": true,
                "name": "ViaBackwards",
                "version": "4.10.2",
                "main": "com.viaversion.viabackwards.BukkitPlugin",
                "authors": [
                    "Matsv",
                    "kennytv",
                    "Gerrygames",
                    "creeper123123321",
                    "ForceUpdate1",
                    "EnZaXD"
                ]
            },
            {
                "enabled": true,
                "name": "Chunky",
                "version": "1.4.10",
                "main": "org.popcraft.chunky.ChunkyBukkit",
                "authors": [
                    "pop4959"
                ]
            },
            {
                "enabled": true,
                "name": "InvSeePlusPlus",
                "version": "0.27.0",
                "main": "com.janboerman.invsee.spigot.InvseePlusPlus",
                "authors": [
                    "Jannyboy11"
                ]
            },
            {
                "enabled": true,
                "name": "PluginConstructorAPI",
                "version": "1.0.50",
                "main": "me.zombie_striker.pluginconstructor.PluginConstructorAPI",
                "authors": [
                    "Zombie_Striker"
                ]
            },
            {
                "enabled": true,
                "name": "BlockLocker",
                "version": "1.12.2",
                "main": "nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl",
                "authors": [
                    "Rutger Kok"
                ]
            },
            {
                "enabled": true,
                "name": "spark",
                "version": "1.10.34",
                "main": "me.lucko.spark.bukkit.BukkitSparkPlugin",
                "authors": [
                    "Luck"
                ]
            },
            {
                "enabled": true,
                "name": "papercurrency",
                "version": "4.9",
                "main": "vb.$papercurrency.PluginMain",
                "authors": [
                    "portal2001"
                ]
            },
            {
                "enabled": true,
                "name": "Logger",
                "version": "1.8.0.15",
                "main": "me.prism3.logger.Logger",
                "authors": [
                    "Prism3",
                    "Sidna"
                ]
            },
            {
                "enabled": true,
                "name": "LandClaiming",
                "version": "1.4.11",
                "main": "me.zombie_striker.landclaiming.LandClaiming",
                "authors": [
                    "Zombie_Striker"
                ]
            },
            {
                "enabled": true,
                "name": "Geyser-Spigot",
                "version": "2.3.2-SNAPSHOT",
                "main": "org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "enabled": false,
                "name": "Novaconomy",
                "version": "1.10.0",
                "main": "us.teaminceptus.novaconomy.Novaconomy",
                "authors": [
                    "Team Inceptus"
                ]
            },
            {
                "enabled": true,
                "name": "ViaRewind",
                "version": "3.1.2",
                "main": "com.viaversion.viarewind.BukkitPlugin",
                "authors": [
                    "FlorianMichael/EnZaXD",
                    "Gerrygames",
                    "creeper123321123"
                ]
            }
        ]
    },
    "flagsInfo": {
        "flags": [
            "-Xms128M",
            "-XX:MaxRAMPercentage=95.0"
        ]
    },
    "extensionInfo": [
        {
            "enabled": true,
            "name": "MCXboxBroadcast",
            "version": "1.0",
            "apiVersion": "1.0.1",
            "main": "com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension",
            "authors": [
                "rtm516"
            ]
        }

**Comment by rtm516** [comment]
The extension dump is 
mcxboxbroadcast dumpsession

**Comment by rtm516** [comment]
Ah your on the 1.21 build of geyser, try updating the extension

**Comment by L642207** [comment]
I updated the extension and the issue still persists. Here is the dump. 

{"membersInfo":{"first":0,"next":2,"count":1,"accepted":1,"active":1},"constants":{"system":{"readyRemovalTimeout":240000,"reservedRemovalTimeout":240000,"sessionEmptyTimeout":0,"inactiveRemovalTimeout":300000,"version":1,"maxMembersCount":30,"visibility":"open","capabilities":{"connectivity":true,"connectionRequiredForActiveMembers":true,"gameplay":true,"crossPlay":true,"userAuthorizationStyle":true},"inviteProtocol":"game","memberInitialization":{"membersNeededToStart":1}},"custom":{}},"properties":{"system":{"joinRestriction":"followed","readRestriction":"followed","turn":[]},"custom":{"BroadcastSetting":3,"CrossPlayDisabled":false,"Joinability":"joinable_by_friends","LanGame":true,"MaxMemberCount":100,"MemberCount":0,"OnlineCrossPlatformGame":true,"SupportedConnections":[{"ConnectionType":6,"HostIpAddress":"172.18.0.9","HostPort":2215,"RakNetGUID":""}],"TitleId":0,"TransportLayer":0,"levelId":"level","hostName":"The Iridium Empire","ownerId":"2535438934713205","rakNetGUID":"79871288274522957558","worldName":"A city of many fine qualities.","worldType":"Survival","protocol":685,"version":"1.21.0"}},"servers":{},"members":{"0":{"next":2,"joinTime":"2024-06-14T14:36:42.1246387Z","constants":{"system":{"initialize":true,"xuid":"2535438934713205","index":0},"custom":{}},"properties":{"system":{"subscription":{"id":"6be7eab5-1d53-440d-a0a9-ac756be319e7","changeTypes":["everything"]},"active":true,"connection":"c5a40bd2-1a7f-473e-8910-3c02b80c6d5a"},"custom":{}},"gamertag":"Ir Empire7187","activeTitleId":"1739947436"}},"correlationId":"3e64ed0b-6534-a3a7-5914-0f8d1e0e3d66","contractVersion":107,"branch":"14d03c1d-8687-497f-916c-22a3ad119de9","changeNumber":8,"startTime":"2024-06-14T14:36:42.1246387Z"}

**Comment by rtm516** [comment]
Your running the tool in a docker container and haven't configured the address in the config, please do that it will fix the problem

**Comment by L642207** [comment]
I apologize for my ignorance, but I don’t know what that means.
