### ISSUE TITLE
unable to connect to world

### ISSUE THREAD

**Issue by sennby** [rtm516/MCXboxBroadcast#85]
My previous one was closed before i could test.
Cannot connect to world. I can add the friend, but when you try to actually join the server, it gets cannot connect to world.

Bedrock players on this address works fine for everyone, only through add friends mcxbox it does this error. 
[lastSessionResponse.json](https://github.com/user-attachments/files/15750588/lastSessionResponse.json)

[currentSessionResponse.json](https://github.com/user-attachments/files/15750587/currentSessionResponse.json)

**Comment by rtm516** [comment]
From what I can see the session and tool is working properly. The issue must be in the clients connecting or the firewall configuration on the server blocking certain connections.

Ive given it another test from my PC and not had an issue adding the bot and connecting.

**Comment by sennby** [comment]
This issue is only from xbox. Xbox players cant join from this tool. Testing from your PC wont give you issues..
What would the firewall be blocking? I have someone on the same host as me using this tool but they have had it setup for months and it works. So nothing should be blocked if his is working on the same host without adding any special ports or anything
