### ISSUE TITLE
Xbox players outside of the home unable to load world.

### ISSUE THREAD

**Issue by Keverino1st** [rtm516/MCXboxBroadcast#87]
Im not sure how to show logs and im not sure if this is a broadcast issue, my local players can join fine and the xbox players can see the server, but are unable to load the world.

**Comment by Isaac-Cooper** [comment]
It's an issue with your server, you need to make sure you port forward the server otherwise players will not be able to connect. You can do this with your router, if your router is unable to port forward, or if you do not know how, I can provide cheap hosting for your server with support on issues in the future, just let me know.

**Comment by Snoaux248** [comment]
Shouldn't Xbox Live be able to handle incoming connections though? through tunneling, like on console?

**Comment by Keverino1st** [comment]
> It's an issue with your server, you need to make sure you port forward the server otherwise players will not be able to connect. You can do this with your router, if your router is unable to port forward, or if you do not know how, I can provide cheap hosting for your server with support on issues in the future, just let me know.

I have port forwarded the ports in use, 19132 isnt showing open for some reason however all other ports are open so im not sure the issue there. The consoles see the server and locals can play on it, external consoles say "cannot connect to world" or load it or something. 

> Shouldn't Xbox Live be able to handle incoming connections though? through tunneling, like on console?

You can apparently connect with apps like bedrock connect and i assumed xboxbroadcast, but im having issues with something.

**Comment by Isaac-Cooper** [comment]
Yes, it's the issue with your router, you will need to use a different hosting service that supports this, you can use my hosting if you want just private message me.

**Comment by rtm516** [comment]
> Shouldn't Xbox Live be able to handle incoming connections though? through tunneling, like on console?

Yes it can, there's been some recent work in looking into how bedrock does this but due to it's complexity I have no current plans to look at implementing it.
