### ISSUE TITLE
Bedrock server support

### ISSUE THREAD

**Issue by Snoaux248** [rtm516/MCXboxBroadcast#88]
any way to make a modified bedrock server that hosts on the Xbox network, without port forwarding as a necessity, kinda like what happens when you create a Single player world.

**Comment by rtm516** [comment]
Not yet, there's been recent work into this in other projects but not something I'm planning on adding anytime soon.

https://github.com/df-mc/nethernet-spec

The tool however will work for a vanilla bedrock server if you port forwarding like normal and adjust the config as required

**Comment by Snoaux248** [comment]
Nope won't work, I need something that replaces the need for port forwarding due to service provider restrictions.

**Comment by rtm516** [comment]
Your best using playit.gg then as that will allow what you want
