### ISSUE TITLE
Can't find binaries

### ISSUE THREAD

**Issue by teknixstuff** [rtm516/MCXboxBroadcast#9]
Sorry about this not really being an issue with the program, but I can't find where to get binaries! Do you provide builds as a plugin/mod, have them hidden in a tab I haven't found, or just not provide builds at all?

**Comment by JulianICE08935** [comment]
OK thanks

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by teknixstuff** [comment]
> Click the 'build passing' badge on the readme.md to download binaries from the CI. I think a download link should be added to the same place.

Thanks!
