### ISSUE TITLE
Can't connect.

### ISSUE THREAD

**Issue by LittleDuck363** [rtm516/MCXboxBroadcast#92]
So I was using the extension to connect to my Network but I am now struggling to get it to connect. It's been a month. Everything is set up correctly and has been completely redone to ensure it's all set and players still can't connect. Is this an issue due to us switching to velocity instead of geyser.

**Comment by rtm516** [comment]
Please provide a session dump and a screenshot of the error message you are getting
`mcxboxbroadcast dumpsession`

**Comment by rtm516** [comment]
Try updating the extension and if that fails then alter the extension config `remote-address` to be the ip for the server that players can use

**Comment by LittleDuck363** [comment]
I'm using the latest extension tho?

**Comment by LittleDuck363** [comment]
That worked, I didn't realized you just updated. Thank you!
