### ISSUE TITLE
Newest StandAlone jar is not adding Players back

### ISSUE THREAD

**Issue by wschris1** [rtm516/MCXboxBroadcast#94]
We updated from an old jar, to a new jar
Server turned on no errors, Didn't add player back when testing
deleted logs and cache and re connected the account. Didn't add player back

Do we need to make a whole new account for it to work?

**Comment by rtm516** [comment]
No its currently a bug in the tool, I plan to have a fix out ASAP

**Comment by rtm516** [comment]
Fixed in https://github.com/rtm516/MCXboxBroadcast/commit/926b49d84f80ad55ac21a79e83ee5cde5b164343 (build 31+)
