### ISSUE TITLE
xbox players cant join

### ISSUE THREAD

**Issue by pxpss** [rtm516/MCXboxBroadcast#99]
i added the extension and it worked at first... after stopping the server and starting it back up a few hours later, xbox players still see the server available to join from friends tab... but says unable to join world.

**Comment by rtm516** [comment]
Please provide a session dump 
mcxboxbroadcast dumpsession

**Comment by pxpss** [comment]
{"membersInfo":{"first":0,"next":2,"count":1,"accepted":1,"active":1},"constants":{"system":{"readyRemovalTimeout":240000,"reservedRemovalTimeout":240000,"sessionEmptyTimeout":0,"inactiveRemovalTimeout":300000,"version":1,"maxMembersCount":30,"visibility":"open","capabilities":{"connectivity":true,"connectionRequiredForActiveMembers":true,"gameplay":true,"crossPlay":true,"userAuthorizationStyle":true},"inviteProtocol":"game","memberInitialization":{"membersNeededToStart":1}},"custom":{}},"properties":{"system":{"joinRestriction":"followed","readRestriction":"followed","turn":[]},"custom":{"BroadcastSetting":3,"CrossPlayDisabled":false,"Joinability":"joinable_by_friends","LanGame":true,"MaxMemberCount":100,"MemberCount":0,"OnlineCrossPlatformGame":true,"SupportedConnections":[{"ConnectionType":6,"HostIpAddress":"pxpss.aternos.me","HostPort":14072,"RakNetGUID":""}],"TitleId":0,"TransportLayer":0,"levelId":"level","hostName":"Geyser","ownerId":"2535410249176618","rakNetGUID":"78899885450740929118","worldName":"Another Geyser server.","worldType":"Survival","protocol":685,"version":"1.21.0/1.20.1"}},"servers":{},"members":{"0":{"next":2,"joinTime":"2024-06-30T23:01:26.4334697Z","constants":{"system":{"initialize":true,"xuid":"2535410249176618","index":0},"custom":{}},"properties":{"system":{"subscription":{"id":"ec9ea419-d390-4387-be3e-ffbc5d60e54c","changeTypes":["everything"]},"active":true,"connection":"723955b6-ec6d-4aa0-bfc1-ac6e1a674c66"},"custom":{}},"gamertag":"pxpss1","activeTitleId":"1739947436"}},"correlationId":"8c520891-81a9-abc0-8a8e-cd73a6400c38","contractVersion":107,"branch":"9a62d51f-dad0-4203-91c5-6d2fdcc98852","changeNumber":20,"startTime":"2024-06-30T23:01:26.4334697Z"}

**Comment by rtm516** [comment]
Looks to be an issue with your geyser install. I suggest checking that it working correctly and if it looks to be then might be worth contacting aternos.

Can't even ping the bedrock server 
https://mcsrvstat.us/bedrock/pxpss.aternos.me:14072

**Comment by pxpss** [comment]
ugh lol thank you... im pretty new to this to i just wanted to play w my friends on xbox... not sure really how to do this all too too well but thank you for your help
